### ISSUE TITLE
 program stops working when the pyacoustid module tries to identify a music file.

### ISSUE THREAD

**Issue by WK-GiHu** [yasath/pyorganise#1]
@yasath 

>From looking at various logs and testing different options, I'm reasonably certain that the issue arises when the module tries to use the command-line tool fpcalc to generate an audio fingerprint.

Searched the [pyorganise.py](https://github.com/yasath/pyorganise/blob/master/pyorganise.py) but didn't find any usage of `fpcalc`?

Please point to the codeline.

**Comment by yasath** [comment]
I compile the program by passing `PyInstaller` the `gui.py` file. This then references `pyorganise.py` which references `extra_id.py` which finally references `metadata_tag/music_tag.py`.

On line 11 of `music_tag.py`, I use the function `acoustid.match` which [uses `fpcalc`](https://github.com/beetbox/pyacoustid/blob/master/README.rst#installation). Sorry if this wasn't clear.

**Comment by WK-GiHu** [comment]
@yasath 

>https://github.com/yasath/pyorganise/blob/534c4a1a3bd8f3eff922ec90cff9373d1622c1d4/metadata_tag/music_tag.py#L11

This env variable get used:
[`fpcalc = os.environ.get(FPCALC_ENVVAR, FPCALC_COMMAND)`](https://github.com/beetbox/pyacoustid/blob/c41e1cca129b427b7f31b853b26538b2326df0da/acoustid.py#L287), 
make sure at least **one** are set to a valid value.
Read: [os.environ](https://docs.python.org/3/library/os.html#os.environ)

There are multiple error conditions, [`except OSError as exc:`](https://github.com/beetbox/pyacoustid/blob/c41e1cca129b427b7f31b853b26538b2326df0da/acoustid.py#L290), show the **REAL** error message you are getting.
